### PR TITLE
Fix the drag problem on Firefox

### PR DESCRIPTION
**Pull request by paucls**
PR with a fix for the drag not working in Firefox.

### CODE REVIEW

**Comment by ggoodman** [comment]
I think that this issue is already addressed by https://github.com/ggoodman/angular-drag-drop/blob/master/src/angular-drag-drop.js#L122-L127. Can you please confirm?

Setting the `dragData` to a non-empty string results in unexpected behaviour with other tools listening on `dragover` and `drop`.

**Comment by paucls** [comment]
Hello,
no, it does not work in Firefox, at least it does not work when I use it in my app. In Chrome is fine.

I think the code you added to fix that

```
if (e.dataTransfer) {
                    if ((!e.dataTransfer.items || !e.dataTransfer.items.length)
                        && (!e.dataTransfer.files || !e.dataTransfer.files.length)) {
                            e.dataTransfer.setData('text', '');
                        }
                }
```

does not do anything because e.dataTransfer is always undefined.

To make it work it needs to use e.originalEvent.dataTransfer.

```
if (e.originalEvent.dataTransfer) {
                        if ((!e.originalEvent.dataTransfer.items || !e.originalEvent.dataTransfer.items.length)
                            && (!e.originalEvent.dataTransfer.files || !e.originalEvent.dataTransfer.files.length)) {
                            e.originalEvent.dataTransfer.setData('text', '');
                        }
                    }
```

I can update my PR, removing the line of code I introduced and fixing the block of code above.

**Comment by paucls** [comment]
Updated PR, please take another look.

**Comment by ggoodman** [comment]
LGTM. Thanks for your work @paucls.

**Pull request merged**
